// This file is automatically generated from your CSS. Any edits will be overwritten.
export const cartProvider: string;
export const cartItems: string;
export const cartItem: string;
export const cartItemPrices: string;
export const cartItemTotal: string;
export const cartSubtotal: string;
export const cartSubtotalText: string;
export const cartCheckout: string;
