// This file is automatically generated from your CSS. Any edits will be overwritten.
export const body: string;
export const bcComponent: string;
export const a11YDialog: string;
export const a11YDialogOverlay: string;
export const a11YDialogContent: string;
export const a11YDialogCloseButton: string;
